version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: graphify_db
    restart: always
    environment:
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
      POSTGRES_DB: graphify
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: graphify_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@graphify.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: